name: Junaid Farooq
description: Ruby, Elixir, DevOps
meta_description: "Ruby, Elixir, DevOps"

aboutPage: true
github: [metadata]

markdown: kramdown
highlighter: rouge
livereload: true

plugins: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'https://ijunaidfarooq.com/'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
