name: Junaid Farooq
title: Junaid Farooq
description: Ruby, Elixir, DevOps
meta_description: "Ruby, Elixir, DevOps"

aboutPage: true
github: [metadata]

markdown: kramdown
highlighter: rouge
livereload: true

plugins: [jekyll-paginate]
paginate: 20
baseurl: ""
domain_name: 'https://ijunaidfarooq.com/'

permalink: /:year/:month/:day/:title
